CREATE DATABASE DOCE_SAEP_DB;
USE DOCE_SAEP_DB;

CREATE TABLE USUARIO (
    USU_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    USU_NOME VARCHAR(255),
    USU_EMAIL VARCHAR(255),
    USU_SENHA VARCHAR(255)
);

CREATE TABLE DOCE (
    DOCE_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    DOCE_NOME VARCHAR(255),
    DOCE_DESCRICAO VARCHAR(255),
    DOCE_FORNECEDOR VARCHAR(255),
    DOCE_CATEGORIA VARCHAR(255),
    DOCE_PRAZO_VALIDADE DATE,
    DOCE_PRIORIDADE_REPOSICAO VARCHAR(255),
    FK_USU_ID INTEGER 
);

CREATE TABLE LOGS (
    LOG_ID INTEGER AUTO_INCREMENT AUTO_INCREMENT PRIMARY KEY,
    LOG_DESCRICAO VARCHAR(255),
    LOG_DATA_HORA DATE
);

CREATE TABLE ESTOQUE (
    ESTOQUE_ID INTEGER AUTO_INCREMENT  PRIMARY KEY,
    ESTOQUE_QUANTIDADE INTEGER,
    FK_DOCE_ID INTEGER 
);
 
ALTER TABLE DOCE ADD CONSTRAINT FK_DOCE_2
    FOREIGN KEY (FK_USU_ID)
    REFERENCES USUARIO (USU_ID);
 
ALTER TABLE ESTOQUE ADD CONSTRAINT FK_ESTOQUE_2
    FOREIGN KEY (FK_DOCE_ID)
    REFERENCES DOCE (DOCE_ID);

    INSERT INTO USUARIO (USU_EMAIL, USU_SENHA, USU_NOME)
VALUES 				("gabriel@email.com","12345678", "Gabriel"),
					("leo@email.com","874659757", "Leonardo"),
					("luiz@email.com","@123@456", "Luiz");

INSERT INTO DOCE 	( DOCE_NOME, DOCE_DESCRICAO, DOCE_FORNECEDOR, DOCE_CATEGORIA,DOCE_PRAZO_VALIDADE,  DOCE_PRIORIDADE_REPOSICAO, FK_USU_ID )
VALUES 				("Bomba","Chocolate","Lorena Gonçalo","Delícia","2025-10-20","Alta",1),
                    ("Bolo","Formigueiro","Alexandre Leonardo","Massa","2025-10-09","Baixa",1),
                    ("Carolina","Carolina de limão","Sophia Carneiro","Doce","2025-10-05","Média",1);
				

INSERT INTO  ESTOQUE (ESTOQUE_QUANTIDADE, FK_DOCE_ID)
VALUES 				(5,1),
					(10,2),
                    (20,3);