CREATE DATABASE ELETRODOMESTICO_SAEP_DB;
USE ELETRODOMESTICO_SAEP_DB;

-- TABELA DE USUÁRIOS
CREATE TABLE USUARIO (
    USU_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    USU_NOME VARCHAR(255),
    USU_EMAIL VARCHAR(255),
    USU_SENHA VARCHAR(255)
);

-- TABELA DE PRODUTOS
CREATE TABLE PRODUTO (
    PROD_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    PROD_NOME VARCHAR(255),
    PROD_DESCRICAO VARCHAR(255),
    PROD_FORNECEDOR VARCHAR(255),
    PROD_CATEGORIA VARCHAR(255),
    PROD_POTENCIA VARCHAR(255),
    PROD_CONSUMO_ENERGETICO VARCHAR(255),
    PROD_GARANTIA VARCHAR(255),
    PROD_PRIORIDADE_REPOSICAO VARCHAR(255),
    FK_USU_ID INTEGER,
    CONSTRAINT FK_PRODUTO_2 FOREIGN KEY (FK_USU_ID)
        REFERENCES USUARIO(USU_ID)
);

-- TABELA DE ESTOQUE
CREATE TABLE ESTOQUE (
    ESTOQUE_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    ESTOQUE_QUANTIDADE INTEGER,
    FK_PROD_ID INTEGER,
    CONSTRAINT FK_ESTOQUE_1 FOREIGN KEY (FK_PROD_ID)
        REFERENCES PRODUTO(PROD_ID)
);

-- TABELA DE LOGS
CREATE TABLE LOGS (
    LOG_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    LOG_DESCRICAO VARCHAR(255),
    LOG_DATA DATE
);

-- INSERINDO DADOS NA TABELA USUARIO
INSERT INTO USUARIO (USU_NOME, USU_EMAIL, USU_SENHA)
VALUES 
('Ana Souza', 'ana.souza@eletroloja.com', '123456'),
('Carlos Pereira', 'carlos.pereira@eletroloja.com', 'senha123'),
('Mariana Lima', 'mariana.lima@eletroloja.com', 'admin2024');

-- INSERINDO DADOS NA TABELA PRODUTO
INSERT INTO PRODUTO (PROD_NOME, PROD_DESCRICAO, PROD_FORNECEDOR, PROD_CATEGORIA, 
PROD_POTENCIA, PROD_CONSUMO_ENERGETICO, PROD_GARANTIA, PROD_PRIORIDADE_REPOSICAO, FK_USU_ID)
VALUES
('Geladeira Frost Free 400L', 'Geladeira moderna com baixo consumo energético', 'EletroPlus', 'Geladeiras', '500W', 'A++', '2 anos', 'Alta', 1),
('Fogão 5 bocas MasterChef', 'Fogão com acendimento automático e forno duplo', 'CozinharBem', 'Fogões', '2000W', 'A+', '1 ano', 'Média', 2),
('Aspirador de pó Turbo', 'Aspirador potente e silencioso', 'LimpaTudo', 'Aspiradores de pó', '1500W', 'A+', '6 meses', 'Baixa', 3);

-- INSERINDO DADOS NA TABELA ESTOQUE
INSERT INTO ESTOQUE (ESTOQUE_QUANTIDADE, FK_PROD_ID)
VALUES
(15, 1),
(8, 2),
(25, 3);

-- INSERINDO DADOS NA TABELA LOGS
INSERT INTO LOGS (LOG_DESCRICAO, LOG_DATA)
VALUES
('Cadastro inicial de produtos realizado.', '2025-11-01'),
('Reposição de estoque realizada.', '2025-11-02'),
('Saída de produtos para venda.', '2025-11-03');
